version: "2"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
#  web:
#    build:
#      context: .
#      dockerfile: client/Dockerfile
#    ports:
#      - "3000:3000"
  go:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
